config/routes.rb
Rails.application.routes.draw do


# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    get 'tasks' => 'tasks#index'
    resources :tasks, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end

  end

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    # root to: 'tasks#index'
    get "users/index" => "users#index"
    get "users" => "users#show"
    get "users/mypage/edit" => "users#edit"
    get "users/confirm" => "users#confirm"
    patch "users/withdraw" => "users#withdraw"
    patch "users/update" => "users#update"
    resources :tasks, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      collection do
      get 'search'
      end
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'favorites' => 'favorites#index'
    post '/tasks/:id' => 'tasks#done',   as: 'done'
    resources :groups, only: [:index, :show, :create, :edit, :update] do
      resource :group_users, only: [:create, :destroy]
    end
    resources :genres, only: [:index, :create, :edit, :update, :show, :destroy]
  end
  root to: 'homes#top'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/favroite.rb
class Favroite < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :tasks
  validates :name, presence: true, uniqueness: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, source: :user
  validates :name, presence: true
  validates :introduction, presence: true

  def is_owned_by?(user)
    owner.id == user.id
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :task
  validates :comment, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :genre, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  validates :genre, presence: true
  validates :due_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthabl
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :tasks, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :email, presence: true, uniqueness: true

  def full_name
    first_name + ' ' + last_name
  end

  def full_name_kana
    first_name_kana + ' ' + last_name_kana
  end
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  def after_sign_in_path_for(_resource_or_scope)
    admin_tasks_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_q, only: [:index, :search]

  def index
    @task = Task.new
    # @tasks = Task.where(done_at:nil)
    @q = Task.all.ransack(params[:q])
    @tasks = @q.result.page(params[:page]).per(40)
  end

  def show
    @task = Task.find(params[:id])
  end

  # def done
  #   @today = Date.today
  #   task = Task.find(params[:id])
  #   task.update(done_at: @today )
  #   redirect_to tasks_path
  # end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to admin_tasks_path
  end

  def search
    @results = @q.result
  end

  private

  def set_q
    @q = Task.ransack(params[:q])
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page])
  end

  def show
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    @user.update(is_active: false)
    redirect_to admin_users_path
  end

  def confirm
  end

  def withdraw
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/tasks_helper.rb
module Admin::TasksHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/tasks/index.html.erb
<div class='container-fluid'>

	<div class='row'>
		<div class="col-md-8"><span><h1>タスク一覧</h1></span></div>
		<div class="col-md-4">
				<form class="form-inline mt-2 mt-md-0">
				<%= search_form_for @q, url: search_tasks_path do |f| %>
				  <%= f.search_field :title_cont, class: "form-control mr-sm-2"%>
				  <span class="input-group-btn">
					  <%= f.submit '検索',class: "btn btn-info" %>
				   </span>
			  <% end %>
			   </form>
		</div>

		<div class="col-md-13">

				<table id="dtBasicExample" class="table" cellspacing="0" width="100%">
			  <thead>
			    <tr>
			    	<th class="th-sm">ID
			    	</th>
			      <th class="th-sm">件名
			    	</th>
			      <th class="th-sm">ジャンル
			    	</th>
			      <th class="th-sm">内容
			      </th>
			      <th class="th-sm">納期
			      </th>
			      <th class="th-sm">担当者
			      </th>
			      <th class="th-sm">機能
			      </th>

			    </tr>
			  </thead>
				<tbody class="example">
					<% @tasks.order(due_date: :asc).each do |task| %>
							<% if (task.due_date - Date.today) < 0 %>
								<tr class="over-head">
									<td><%= task.id %></td>
									<td ><%= task.title %></td>
									<td><%= Genre.find(task.genre_id).name %></td>
									<td><%= task.body %></td>
									<td><%= task.due_date.strftime("%m/%d") %></td>
									<td><%= task.person_name %></td>
									<td>
										<%= link_to "詳細", admin_task_path(task), class: "btn btn-primary" %>
										コメント数: <%= task.post_comments.count %>
							
										
									</td>
								</tr>
								<% elsif(task.due_date - Date.today) <= 7 %>
								<tr class="danger-head">
									<td><%= task.id %></td>
									<td ><%= task.title %></td>
									<td><%= Genre.find(task.genre_id).name %></td>
									<td><%= task.body %></td>
									<td><%= task.due_date.strftime("%m/%d") %></td>
									<td><%= User.find(task.user_id).last_name %></td>
									<td>
										<%= link_to "詳細", admin_task_path(task), class: "btn btn-primary" %>
										コメント数: <%= task.post_comments.count %>
									</td>
								</tr>
							<% else(task.due_date - Date.today)%>
								<tr class="t-head">
									<td><%= task.id %></td>
									<td ><%= task.title %></td>
									<td><%= Genre.find(task.genre_id).name %></td>
									<td><%= task.body %></td>
									<td><%= task.due_date.strftime("%m/%d") %></td>
									<td><%= User.find(task.user_id).last_name %></td>
									<td>
										<%= link_to "詳細", admin_task_path(task), class: "btn btn-primary" %>
										コメント数: <%= task.post_comments.count %>

									</td>
								</tr>
							<% end %>
				 <% end %>
		  	</tbody>
			</table>
		 </div>
	</div>
	<%= paginate @tasks %>
</div>

app/views/admin/tasks/show.html.erb
<div style="margin-top : 100px"></div>
<div class='container_fluid'>
  <h2>タスク詳細</h2>
  <table id="dtBasicExample" class="table" cellspacing="0" width="100%">
    <thead>
        <tr>
        	<th class="th-sm">ID
        	</th>
          <th class="th-sm">件名
        	</th>
          <th class="th-sm">ジャンル
        	</th>
          <th class="th-sm">内容
          </th>
          <th class="th-sm">納期
          </th>
          <th class="th-sm">担当者
          </th>
          <th class="th-sm">機能
          </th>
        </tr>
      </thead>
      <tbody>
    				<tr>
    					<td><%= @task.id %></td>
    					<td ><%= @task.title %></td>
    					<td><%= Genre.find(@task.genre_id).name %></td>
    					<td><%= @task.body %></td>
    					<td><%= @task.due_date %></td>
    					<td><%= @task.person_name %></td>
    					<td>
    						コメント数: <%= @task.post_comments.count %>
    						<%= link_to "削除", admin_task_path(@task), method: :delete, "data-confirm" => "削除します。本当によろしいですか？", class: "btn btn-danger" %>
    					</td>
    				</tr>
    </tbody>
  </table>
      <div class="post-comments-index">
        <%= render "admin/post_comments/index", task: @task %>
      </div>

    </div>
<%= link_to '一覧へ', admin_tasks_path %>
</div>

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<div class='container_fluids'>
      <h2>ユーザー一覧</h2>
    <div class='col-md-8'>
      <table class='table'>
        <thead>
          <tr>
          <th>ID</th>
      		<th>名前</th>
      		<th>フリガナ</th>
      		<th>メールアドレス</th>
      		<th>電話番号</th>
      		<th>備考</th>
      		<th>ユーザーステータス(false退会)</th>
      		<th>機能</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.full_name %></td>
              <td><%= user.full_name_kana %></td>
              <td><%= user.email %></td>
              <td><%= user.telephone_number %></td>
              <td><%= user.introduction %></td>
              <td><%= user.is_active %></td>
              <td><%= link_to "退会", admin_user_path(user), method: :patch, "data-confirm" => "OKを押すと退会処理がされます。本当によろしいですか？", class: "btn btn-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>