config/routes.rb
Rails.application.routes.draw do


# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    get 'tasks' => 'tasks#index'
    resources :tasks, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end

  end

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    # root to: 'tasks#index'
    get "users/index" => "users#index"
    get "users" => "users#show"
    get "users/mypage/edit" => "users#edit"
    get "users/confirm" => "users#confirm"
    patch "users/withdraw" => "users#withdraw"
    patch "users/update" => "users#update"
    resources :tasks, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      collection do
      get 'search'
      end
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'favorites' => 'favorites#index'
    post '/tasks/:id' => 'tasks#done',   as: 'done'
    resources :groups, only: [:index, :show, :create, :edit, :update] do
      resource :group_users, only: [:create, :destroy]
    end
    resources :genres, only: [:index, :create, :edit, :update, :show, :destroy]
  end
  root to: 'homes#top'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/favroite.rb
class Favroite < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :tasks
  validates :name, presence: true, uniqueness: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, source: :user
  validates :name, presence: true
  validates :introduction, presence: true

  def is_owned_by?(user)
    owner.id == user.id
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :task
  validates :comment, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :genre, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  validates :genre, presence: true
  validates :due_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthabl
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :tasks, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :email, presence: true, uniqueness: true

  def full_name
    first_name + ' ' + last_name
  end

  def full_name_kana
    first_name_kana + ' ' + last_name_kana
  end
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_q, only: [:index, :search]

  def index
    @task = Task.new
    # @tasks = Task.where(done_at:nil)
    @q = Task.all.ransack(params[:q])
    @tasks = @q.result.page(params[:page]).per(40)
  end

  def show
    @task = Task.find(params[:id])
  end

  # def done
  #   @today = Date.today
  #   task = Task.find(params[:id])
  #   task.update(done_at: @today )
  #   redirect_to tasks_path
  # end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to admin_tasks_path
  end

  def search
    @results = @q.result
  end

  private

  def set_q
    @q = Task.ransack(params[:q])
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page])
  end

  def show
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    @user.update(is_active: false)
    redirect_to admin_users_path
  end

  def confirm
  end

  def withdraw
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/tasks_helper.rb
module Admin::TasksHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskInOut</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <%= link_to "TaskInOut", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "Task list", admin_tasks_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "User list", admin_users_path, class: "nav-link" %>
            </li>
          <% elsif user_signed_in? %>
            <%= link_to "New task", new_task_path, class: "nav-link" %>
            <%= link_to "Task list", tasks_path, class: "nav-link" %>
            <%= link_to "Group", groups_path, class: "nav-link" %>
            <%= link_to "Genre", genres_path, class: "nav-link" %>
            <%= link_to "Contact information", users_index_path, class: "nav-link" %>
            <%= link_to "Bookmark", favorites_path, class: "nav-link" %>
          <% else %>

          <% end %>



        </ul>

          <% if admin_signed_in? %>

            <li><%= link_to 'Log out', destroy_admin_session_path, method: :delete %></li>

          <% elsif user_signed_in? %>
            <li>
              <%= link_to "Log out", destroy_user_session_path, class: "btn btn-warning", method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to "Sign up", new_user_registration_path, class: "btn btn-warning" %>
            </li>
            <li>
              <%= link_to "Sign in", new_user_session_path, class: "btn btn-warning" %>
            </li>
            <li>
              <%= link_to "Admin", new_admin_session_path, class: "btn btn-warning" %>
            </li>
          <% end %>

      </div>
    </nav>
  </header>



  <body>
    <%= yield %>
  </body>


<footer class="footer py-3">
  <div class="container">
    <p>&copy; 20**-20** Company, Inc.</p>
  </div>
</footer>
</html>